# Generated by Django 5.2.15 on 2026-06-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(help_text='The name of the educational institution', max_length=200)),
                ('degree', models.CharField(help_text='The degree or certification you earned', max_length=200)),
                ('field_of_study', models.CharField(help_text='The field of study or major', max_length=200)),
                ('start_date', models.DateField(help_text='The date you started this education')),
                ('end_date', models.DateField(blank=True, help_text='The date you completed this education (leave blank if still ongoing)', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about your education (optional)')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('photo', models.ImageField(help_text='A professional photo of yourself', upload_to='photos/')),
                ('description', models.TextField(help_text='A brief description of yourself')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('main_image', models.ImageField(help_text='The main image representing the project', upload_to='project_images/')),
                ('short_description', models.CharField(help_text='A brief summary of the project (max 255 characters)', max_length=255)),
                ('description', models.TextField(help_text='A detailed description of the project')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_preview_link', models.URLField(blank=True, help_text='Link to a live demo of the project (if available)', null=True)),
                ('created_at', models.DateField(blank=True, help_text='The date the project was created', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The date the project was completed (leave blank if still ongoing)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Niższy = wyżej na liście')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Language', 'Language'), ('Framework', 'Framework'), ('Tool', 'Tool'), ('Other', 'Other')], default='Other', max_length=50)),
                ('name', models.CharField(help_text='The name of the skill (e.g., Python, Django, Git)', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=50)),
                ('description', models.TextField(help_text='A brief description of the skill and your experience with it')),
                ('icon', models.CharField(blank=True, help_text="Devicon class name, e.g. 'devicon-python-plain'", max_length=100)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Niższy = wyżej na liście')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Review',
                'verbose_name_plural': 'Project Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skills_used',
            field=models.ManyToManyField(related_name='projects', to='core.skill'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('skills_earned', models.ManyToManyField(related_name='experiences', to='core.skill')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
